/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DevOnly: typeof import('./src/components/DevOnly.vue')['default']
    DrawerContainer: typeof import('./src/components/DrawerContainer.vue')['default']
    FullscreenPage: typeof import('./src/components/FullscreenPage.vue')['default']
    HeartRateChart: typeof import('./src/components/HeartRateChart.vue')['default']
    HistoryList: typeof import('./src/components/HistoryList.vue')['default']
    LucidePackage: typeof import('./src/components/icons/LucidePackage.vue')['default']
    MarqueeText: typeof import('./src/components/MarqueeText.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer.vue')['default']
    PluginSettingsForm: typeof import('./src/components/PluginSettingsForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanningDevice: typeof import('./src/components/ScanningDevice.vue')['default']
    SessionOverlay: typeof import('./src/components/SessionOverlay.vue')['default']
    SignalIndicator: typeof import('./src/components/SignalIndicator.vue')['default']
    SlideDrawer: typeof import('./src/components/SlideDrawer.vue')['default']
    SolarPlayStreamBold: typeof import('./src/components/icons/SolarPlayStreamBold.vue')['default']
    SolarWidget2BoldDuotone: typeof import('./src/components/icons/SolarWidget2BoldDuotone.vue')['default']
    SvgSpinnersPulse2: typeof import('./src/components/icons/SvgSpinnersPulse2.vue')['default']
    SvgSpinnersWifiFade: typeof import('./src/components/icons/SvgSpinnersWifiFade.vue')['default']
    SystemUiconsSignalFull: typeof import('./src/components/icons/SystemUiconsSignalFull.vue')['default']
    SystemUiconsSignalLow: typeof import('./src/components/icons/SystemUiconsSignalLow.vue')['default']
    SystemUiconsSignalMedium: typeof import('./src/components/icons/SystemUiconsSignalMedium.vue')['default']
    TablerActivityHeartbeat: typeof import('./src/components/icons/TablerActivityHeartbeat.vue')['default']
    TablerBluetooth: typeof import('./src/components/icons/TablerBluetooth.vue')['default']
    TablerBluetoothConnected: typeof import('./src/components/icons/TablerBluetoothConnected.vue')['default']
    TablerBluetoothOff: typeof import('./src/components/icons/TablerBluetoothOff.vue')['default']
    TablerBluetoothX: typeof import('./src/components/icons/TablerBluetoothX.vue')['default']
    TablerCaretDownFilled: typeof import('./src/components/icons/TablerCaretDownFilled.vue')['default']
    TablerCaretUpFilled: typeof import('./src/components/icons/TablerCaretUpFilled.vue')['default']
    TablerDeviceWatch: typeof import('./src/components/icons/TablerDeviceWatch.vue')['default']
    TablerHeartbeat: typeof import('./src/components/icons/TablerHeartbeat.vue')['default']
    TablerHistory: typeof import('./src/components/icons/TablerHistory.vue')['default']
    TablerReload: typeof import('./src/components/icons/TablerReload.vue')['default']
    TablerSearch: typeof import('./src/components/icons/TablerSearch.vue')['default']
    TipsCarousel: typeof import('./src/components/TipsCarousel.vue')['default']
  }
}
